### ISSUE TITLE
MySQL Dialect User Guide - JDBC Driver properties names

### ISSUE THREAD

**Issue by allipatev** [exasol/mysql-virtual-schema#10]
Hello,
In [MySQL Dialect User Guide](https://github.com/exasol/mysql-virtual-schema/blob/main/doc/user_guide/mysql_user_guide.md) JDBC driver settings table contains row for "Name".
At least in Exasol 7.0.7 it is called "Driver Name":
![image](https://user-images.githubusercontent.com/58830344/114538223-6a071600-9c53-11eb-8b1d-7a52690011dd.png)
You may also notice that "Main" in the same table needs to be changed to "Main Class".

**Comment by chiaradiamarcelo** [comment]
Hi @allipatev ,
thanks for the suggestion. We'll update the guide to reflect this.
